# Python Tutorial with Techworldwithnana

▬▬▬▬▬▬ T I M E S T A M P S ⏰  ▬▬▬▬▬▬
1. 0:00 - Course Intro & Course Overview
2. 2:53 - Introduction to Python
3. 07:01 - Installation and Local Setup with PyCharm
4. 14:10 - Write our first Python program
5. 15:33 - Python IDE vs simple File Editor
6. 19:04 - Strings and Number Data Types
7. 30:11 - Variables in Python
8. 39:33 - Encapsulate Logic with Functions
9. 54:00 - Scope
10. 59:50 - Accepting User Input
11. 1:15:28 - Conditionals (if / else) and Boolean Data Type
12. 1:44:18 - Error Handling with Try / Except
13. 1:50:11 -  While Loops
14. 2:02:43 - Lists and For Loops
15. 2:21:51 - Thanks JetBrains!  
16. 2:23:17 - Comments in Python
17. 2:27:23 - Sets
18. 2:38:31 - Built-In Functions
19. 2:44:25 - Dictionary Data Type
20. 3:01:32 - Modularize your project with Modules
21. 3:20:09 - Project: Countdown App
22. 3:40:27 - Packages, PyPI and pip
23. 3:54:06 - Project: Automation with Python (Working with Spreadsheets)
24. 4:44:02 - Object Oriented Programming: Classes and Objects
25. 5:14:35 - Project: API Request to GitLab
26. 5:30:23 - Wrap Up

## 01 Data Type (string and numbers

In [1]:
print("hello bro")
print(2)

hello bro
2


In [2]:
# concatenate
print("20 days are " + str(45) + ' minutes')

20 days are 45 minutes


In [5]:
print(f'20 days are {20*24*60*60} seconds')
print(f'35 days are {20*35*60*60} seconds')
print(f'55 days are {20*55*60*60} seconds')

20 days are 1728000 seconds
35 days are 2520000 seconds
55 days are 3960000 seconds


In [6]:
# using variables
cal_to_sec = 24*60*60
unit = 'second'

In [9]:
#variable helps us to reduce duplication
print(f'30 days are {30 * cal_to_sec} {unit}')

30 days are 2592000 second


## Using Functions: 
These are blocks of codes to perform specific task, which can be usable

In [37]:
sec3 = 24*60*60 # global variable

def cal_sec(x, comment):
    sec2 = 24*60*60 # local variable
    print(f'{x} days are {x* sec2} seconds')
    #print(comment)

In [38]:
cal_sec(5, "Successful !")

5 days are 432000 seconds


In [39]:
u_input = int(input("Enter a number of Days: "))
cal_val = cal_sec(u_input, "Succuessful")
print(cal_val)

Enter a number of Days: 45
45 days are 3888000 seconds
None


In [40]:
cal_sec(3,4)

3 days are 259200 seconds


## Conditional statements

In [49]:
 # conditional statement
sec3 = 24*60*60 # global variable

def days_units(num_days):
    print(num_days > 5)
    print(type(num_days > 5))
    if num_days > 5:
        return f"{num_days} days are {num_days * sec3}"
    else:
        return "OOPs !! you have entered a number less than 5"

In [50]:
days_units(3)

False
<class 'bool'>


'OOPs !! you have entered a number less than 5'

In [48]:
days_units(6)

True


'6 days are 518400'

In [56]:
print('string:', type('ss'), 
      '\n float: ', type(4.55),
     '\n int: ', type(int(4)),
     '\n list: ', type([3,4,5]),
     '\n tuple: ', type((2,3,4)))

string: <class 'str'> 
 float:  <class 'float'> 
 int:  <class 'int'> 
 list:  <class 'list'> 
 tuple:  <class 'tuple'>


In [86]:
# what if user provides string
 # conditional statement
sec3 = 24*60*60 # global variable

def days_units(num_days):
    print(num_days > 0)
    print(type(num_days > 0))
    if num_days > 0:
        return f"{num_days} days are {num_days * sec3}"
    elif num_days ==0:
        print('you entered zero: NOT VALID')
    else:
        return "OOPs !! you have entered a wrong number"

In [87]:
user_in = input("enter a number: ")

if user_in.isdigit():
    user_in_num = int(user_in)
    cal_day = days_units(user_in_num)
    print(cal_day)
else:
    print('Not a number, PLEASE ENTER POSITIVE NUMBERS')

enter a number: 0
False
<class 'bool'>
you entered zero: NOT VALID
None


## Clean up your code

In [80]:
user_in = input("enter a number: ")
def validate_execute(user_in):
    if user_in.isdigit():
        user_in_num = int(user_in)
        cal_day = days_units(user_in_num)
        print(cal_day)
    elif user_in ==0:
        print('you entered zero: NOT VALID')
    else:
        print('Not a number, PLEASE ENTER POSITIVE NUMBERS')

validate_execute(user_in)

enter a number: 0
False
<class 'bool'>
OOPs !! you have entered a number less than 5


In [71]:
validate_execute(user_in)

TypeError: validate_execute() takes 0 positional arguments but 1 was given

In [88]:
import numpy as np

In [96]:
arr = np.random.randint(1,50, size = (3,4))

In [97]:
arr

array([[23, 25, 32, 22],
       [20, 13,  4, 15],
       [10,  7, 38,  2]])

In [104]:
np.argmin(arr, axis =0) # operation via column

array([2, 2, 1, 2])

In [106]:
np.argmin(arr, axis =1) # operation via row

array([3, 2, 3])

In [103]:
np.argmin(arr)

11

In [109]:
#help(np.argmax)

In [112]:
arr2 = np.expand_dims(arr, axis=0) # inserting at possition 0
print(arr2)
print(arr2.shape)

[[[23 25 32 22]
  [20 13  4 15]
  [10  7 38  2]]]
(1, 3, 4)


In [113]:
print(arr)
print(arr.shape)

[[23 25 32 22]
 [20 13  4 15]
 [10  7 38  2]]
(3, 4)


In [114]:
arr3 = np.expand_dims(arr, axis=1) 
# inserting at possition 1
print(arr3)
print(arr3.shape)

[[[23 25 32 22]]

 [[20 13  4 15]]

 [[10  7 38  2]]]
(3, 1, 4)


In [115]:
arr.flatten()

array([23, 25, 32, 22, 20, 13,  4, 15, 10,  7, 38,  2])

In [120]:
x = 0
while x <5:
    print('Hello boy')
    x+=1

Hello boy
Hello boy
Hello boy
Hello boy
Hello boy


In [121]:
# error handling
user_in = input("enter a number: ")
def validate_execute(user_in):
    try:
    if user_in.isdigit():
        user_in_num = int(user_in)
        cal_day = days_units(user_in_num)
        print(cal_day)
    elif user_in ==0:
        print('you entered zero: NOT VALID')
    else:
        print('Not a number, PLEASE ENTER POSITIVE NUMBERS')

validate_execute(user_in)

enter a number: 5
True
<class 'bool'>
5 days are 432000


In [1]:
def validate_and_exe(user_in):
    try:
        user_input = int(user_in)
        if user_input >0:
            cal_day = days_units(user_in_num)
            print(cal_day)
        elif user_input ==0:
            print('You entered Zero: NOt VAlid')
       
    except ValueError:
        print('Your input is not valid')

In [2]:
validate_and_exe(3.9)

NameError: name 'days_units' is not defined

### List and for loop

In [16]:
nn = [1,1,2,2,9,4,4,50]

# write code to output  elements of list with one appearance

for i in range(0, len(nn)):
    cnt = nn.count(nn[i])
    if cnt ==1:
        print(nn[i], 'count = ', nn.count(nn[i]))

9 count =  1
50 count =  1


In [8]:
nn.count(4)

2

In [17]:
my = ['Tony', 'Ekle', 'Anthony']

In [18]:
my[0]

'Tony'

In [19]:
my.append('JetBrains')

In [20]:
my

['Tony', 'Ekle', 'Anthony', 'JetBrains']

In [21]:
' hello guys'

['hello', 'guys']